version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    networks:
      - mynetwork

  web:
    build: .
    container_name: web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
      - rabbitmq
    networks:
      - mynetwork

  worker:
    build: .
    container_name: worker
    command: python3 -m dramatiq app3.tasks --queues high_priority_queue,medium_priority_queue,low_priority_queue
    volumes:
      - .:/app
    depends_on:
      - db
      - rabbitmq
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
